name: nostr_dart
version: 0.6.5
description: A Nostr protocol client API for building censorship-resistant social network applications in Dart/Flutter.
homepage: https://github.com/Satswalker/nostr_dart
repository: https://github.com/Satswalker/nostr_dart
issue_tracker: https://github.com/Satswalker/nostr_dart/issues
environment:
  sdk: '>=2.17.6 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {bip340: ^0.0.4, build_runner: ^2.3.3, clock: ^1.1.1, crypto: ^3.0.2, hex: ^0.2.0, http: ^0.13.5, mockito: ^5.3.2, queue: ^3.1.0+2, string_validator: ^0.3.0, web_socket_channel: ^2.2.0}
