name: nostr_dart
version: 0.2.0
description: A Nostr client library written in Dart
homepage: https://github.com/Satswalker/nostr_dart
repository: https://github.com/Satswalker/nostr_dart
issue_tracker: https://github.com/Satswalker/nostr_dart/issues
environment:
  sdk: '>=2.17.6 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {bip340: ^0.0.4, clock: ^1.1.1, crypto: ^3.0.2, hex: ^0.2.0, string_validator: ^0.3.0, web_socket_channel: ^2.2.0}
